//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLOTHING_SALES_MANAGEMENT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOANGVANTIEBBFD;Initial Catalog=CMU_CS_447_GROUP_PROJECT;User ID=sa;P" +
            "assword=Tiendat@123;TrustServerCertificate=True")]
        public string CMU_CS_447_GROUP_PROJECTConnectionString {
            get {
                return ((string)(this["CMU_CS_447_GROUP_PROJECTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-68GDOI8K\\MAYCUONG;Initial Catalog=CMU_CS_447_GROUP_PROJECT;Int" +
            "egrated Security=True;TrustServerCertificate=True")]
        public string CMU_CS_447_GROUP_PROJECTConnectionString1 {
            get {
                return ((string)(this["CMU_CS_447_GROUP_PROJECTConnectionString1"]));
            }
        }
    }
}
